name: ServerLinks
version: '1.1.2'
main: com.etmisthefox.serverLinks.ServerLinks
#api-version: '1.21'
authors: [ EtmisTheFox ]
description: Add custom website links to your server with dynamic commands and advanced color formatting.
website: https://etmisthefox.com
commands:
  slreload:
    description: Reloads config.yml
    usage: /slreload
    permission: serverlinks.reload
permissions:
  serverlinks.reload:
    description: allows player with this permission to use /slreload
    default: op
